// Build (or rebuild) a composite character sheet for ONE character — lays
// out every available angle (front/side/back/three-quarter/…) on a single
// 1280x720 image so video models always get one reference instead of
// juggling 4-5 separate portraits. Caches the URL on Character.coverUrl
// (or in metadata if no field) so the page can show it immediately.

import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { authenticate, isAuthResponse } from "@/lib/auth";
import { buildCharacterSheet, type SheetCharacter } from "@/lib/character-sheet";
import { put as putBlob } from "@vercel/blob";
import { handleError, ok } from "@/lib/route-utils";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const ctx = await authenticate(req); if (isAuthResponse(ctx)) return ctx;
    const character = await prisma.character.findUnique({
      where: { id: params.id },
      include: { media: { orderBy: { createdAt: "asc" } } },
    });
    if (!character) throw Object.assign(new Error("character not found"), { statusCode: 404 });
    if (character.media.length === 0) throw Object.assign(new Error("no media to composite"), { statusCode: 400 });

    // Each media item becomes a "tile" labeled by its angle (front/side/back/etc.)
    // or "Image N" if no angle metadata. Cap at 4 tiles for legibility.
    const tiles: SheetCharacter[] = character.media.slice(0, 4).map((m, i) => {
      const angle = (m.metadata as { angle?: string } | null)?.angle;
      return { name: angle ? angle.toUpperCase() : `View ${i + 1}`, portraitUrl: m.fileUrl };
    });

    const buf = await buildCharacterSheet(tiles);
    const blob = await putBlob(`character-sheets/${character.id}-${Date.now()}.jpg`, buf, {
      access: "public",
      contentType: "image/jpeg",
      addRandomSuffix: true,
    });

    // Persist the composite as a CharacterMedia row tagged role="composite"
    // so the page can find + display it without changing the Character schema.
    await prisma.characterMedia.create({
      data: {
        characterId: character.id,
        mediaType: "composite",
        fileUrl: blob.url,
        metadata: { angle: "composite", autoGenerated: true, sourceCount: tiles.length, mimeType: "image/jpeg", width: 1280, height: 720 } as any,
      },
    });

    return ok({ compositeUrl: blob.url, tiles: tiles.length });
  } catch (e) {
    return handleError(e);
  }
}

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  // Returns the latest composite if one exists. If not, the page shows the
  // build button (POST) and falls back to individual portraits.
  try {
    const ctx = await authenticate(req); if (isAuthResponse(ctx)) return ctx;
    const latest = await prisma.characterMedia.findFirst({
      where: { characterId: params.id, metadata: { path: ["angle"], equals: "composite" } },
      orderBy: { createdAt: "desc" },
      select: { id: true, fileUrl: true, createdAt: true, metadata: true },
    });
    return ok({ composite: latest });
  } catch (e) {
    return handleError(e);
  }
}
