/**
 * GET  /api/v1/seasons/[id]/opening → current opening + versions
 * PATCH /api/v1/seasons/[id]/opening → update fields. If prompt changes, snapshot old.
 * DELETE /api/v1/seasons/[id]/opening → remove it
 */
import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { authenticate, requirePermission, isAuthResponse } from "@/lib/auth";
import { handleError, ok } from "@/lib/route-utils";
import { pollVeoOperation, priceVeoVideo, type GoogleVeoModel } from "@/lib/providers/google-veo";
import { pollSoraVideo, priceSora, type SoraModel } from "@/lib/providers/openai-sora";

export const runtime = "nodejs"; export const dynamic = "force-dynamic";

async function assertSeason(seasonId: string, orgId: string) {
  const s = await prisma.season.findFirst({
    where: { id: seasonId, series: { project: { organizationId: orgId } } },
    select: { id: true, seriesId: true },
  });
  if (!s) throw Object.assign(new Error("season not found"), { statusCode: 404 });
  return s;
}

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const ctx = await authenticate(req); if (isAuthResponse(ctx)) return ctx;
    await assertSeason(params.id, ctx.organizationId);
    let opening = await prisma.seasonOpening.findUnique({
      where: { seasonId: params.id },
      include: { versions: { orderBy: { createdAt: "desc" }, take: 30 } },
    });

    // If the opening is being generated by Google VEO (no webhook), poll the
    // operation status on every GET so the client sees completion.
    if (opening && opening.provider === "google" && opening.status === "GENERATING" && opening.falRequestId) {
      try {
        const res = await pollVeoOperation(opening.falRequestId);
        if (res.done && res.videoUri) {
          const proxyUrl = `/api/v1/videos/veo-proxy?uri=${encodeURIComponent(res.videoUri)}`;
          await prisma.seasonOpening.update({
            where: { id: opening.id },
            data: { status: "READY", videoUrl: proxyUrl, videoUri: res.videoUri },
          });
          // Register asset + reconcile cost
          const { season: s } = await prisma.seasonOpening.findUniqueOrThrow({
            where: { id: opening.id },
            include: { season: { include: { series: { select: { projectId: true } } } } },
          });
          const projectId = s.series.projectId;
          await prisma.asset.create({
            data: {
              projectId, entityType: "SEASON_OPENING", entityId: opening.id, assetType: "VIDEO",
              fileUrl: proxyUrl, mimeType: "video/mp4", status: "READY",
              metadata: { provider: "google-veo", model: opening.model, durationSeconds: opening.duration, costUsd: priceVeoVideo(opening.model.replace(/^google-/, "") as GoogleVeoModel, opening.duration), uri: res.videoUri } as object,
            },
          }).catch(() => {});
          // refresh after update
          opening = await prisma.seasonOpening.findUnique({
            where: { seasonId: params.id },
            include: { versions: { orderBy: { createdAt: "desc" }, take: 30 } },
          });
        } else if (res.done && res.error) {
          await prisma.seasonOpening.update({
            where: { id: opening.id },
            data: { status: "FAILED" },
          });
          opening = await prisma.seasonOpening.findUnique({
            where: { seasonId: params.id },
            include: { versions: { orderBy: { createdAt: "desc" }, take: 30 } },
          });
        }
      } catch (e) {
        console.warn("[veo-poll]", (e as Error).message);
      }
    }

    // Same polling pattern for OpenAI Sora (also no webhook support).
    if (opening && opening.provider === "openai" && opening.status === "GENERATING" && opening.falRequestId) {
      try {
        const res = await pollSoraVideo(opening.falRequestId);
        if (res.status === "completed") {
          const proxyUrl = `/api/v1/videos/sora-proxy?id=${encodeURIComponent(opening.falRequestId)}`;
          await prisma.seasonOpening.update({
            where: { id: opening.id },
            data: { status: "READY", videoUrl: proxyUrl, videoUri: opening.falRequestId },
          });
          const { season: s } = await prisma.seasonOpening.findUniqueOrThrow({
            where: { id: opening.id },
            include: { season: { include: { series: { select: { projectId: true } } } } },
          });
          const projectId = s.series.projectId;
          await prisma.asset.create({
            data: {
              projectId, entityType: "SEASON_OPENING", entityId: opening.id, assetType: "VIDEO",
              fileUrl: proxyUrl, mimeType: "video/mp4", status: "READY",
              metadata: { provider: "openai-sora", model: opening.model, durationSeconds: opening.duration, costUsd: priceSora(opening.model as SoraModel, opening.duration), soraVideoId: opening.falRequestId } as object,
            },
          }).catch(() => {});
          opening = await prisma.seasonOpening.findUnique({
            where: { seasonId: params.id },
            include: { versions: { orderBy: { createdAt: "desc" }, take: 30 } },
          });
        } else if (res.status === "failed") {
          await prisma.seasonOpening.update({
            where: { id: opening.id },
            data: { status: "FAILED" },
          });
          opening = await prisma.seasonOpening.findUnique({
            where: { seasonId: params.id },
            include: { versions: { orderBy: { createdAt: "desc" }, take: 30 } },
          });
        }
      } catch (e) {
        console.warn("[sora-poll]", (e as Error).message);
      }
    }
    // Every successful fal generation creates an Asset row tagged to this opening.
    // Surface the full list so the UI can show "generation #N · model · cost · when".
    const videoHistory = opening
      ? await prisma.asset.findMany({
          where: { entityType: "SEASON_OPENING", entityId: opening.id, assetType: "VIDEO", status: "READY" },
          orderBy: { createdAt: "desc" },
          take: 30,
          select: { id: true, fileUrl: true, createdAt: true, metadata: true },
        })
      : [];
    // Aggregate every CostEntry attributed to this season's opening (text AI +
    // video generation). Both are tagged entityType=SEASON_OPENING + entityId=seasonId.
    const costs = await prisma.costEntry.findMany({
      where: { entityType: "SEASON_OPENING", entityId: params.id },
      orderBy: { createdAt: "desc" },
    });
    let textCost = 0, videoCost = 0;
    for (const c of costs) {
      if (c.costCategory === "TOKEN") textCost += c.totalCost;
      else if (c.costCategory === "GENERATION") videoCost += c.totalCost;
    }
    return ok({
      opening,
      costBreakdown: {
        text: +textCost.toFixed(6),
        video: +videoCost.toFixed(6),
        total: +(textCost + videoCost).toFixed(6),
        calls: costs.length,
        entries: costs.map((c) => ({ id: c.id, category: c.costCategory, description: c.description, cost: c.totalCost, at: c.createdAt })),
      },
      videoHistory: videoHistory.map((a) => {
        const m = (a.metadata as { model?: string; durationSeconds?: number; costUsd?: number } | null) ?? {};
        return {
          id: a.id,
          fileUrl: a.fileUrl,
          at: a.createdAt,
          model: m.model ?? null,
          durationSeconds: m.durationSeconds ?? null,
          costUsd: m.costUsd ?? null,
        };
      }),
    });
  } catch (e) { return handleError(e); }
}

const Patch = z.object({
  prompt: z.string().min(1).optional(),
  duration: z.number().int().min(1).max(20).optional(),
  aspectRatio: z.enum(["16:9", "9:16", "1:1"]).optional(),
  model: z.enum([
    "seedance", "kling", "veo3-fast", "veo3-pro",
    "google-veo-3.1-fast-generate-preview", "google-veo-3.1-generate-preview", "google-veo-3.1-lite-generate-preview",
    "sora-2", "sora-2-pro",
  ]).optional(),
  isSeriesDefault: z.boolean().optional(),
  includeCharacters: z.boolean().optional(),
  characterIds: z.array(z.string()).optional(),
  styleLabel: z.string().optional(),
  status: z.enum(["DRAFT", "GENERATING", "READY", "FAILED"]).optional(),
});

export async function PATCH(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const ctx = await authenticate(req); if (isAuthResponse(ctx)) return ctx;
    const f = requirePermission(ctx, "edit_project"); if (f) return f;
    const body = Patch.parse(await req.json());
    const season = await assertSeason(params.id, ctx.organizationId);

    const existing = await prisma.seasonOpening.findUnique({ where: { seasonId: params.id } });
    if (!existing) throw Object.assign(new Error("opening not found — create one first"), { statusCode: 404 });

    // Snapshot prompt BEFORE overwriting
    if (body.prompt && body.prompt !== existing.currentPrompt) {
      await prisma.seasonOpeningPromptVersion.create({
        data: { openingId: existing.id, prompt: existing.currentPrompt },
      });
    }

    const updateData: Record<string, unknown> = {};
    if (body.prompt !== undefined) updateData.currentPrompt = body.prompt;
    if (body.duration !== undefined) updateData.duration = body.duration;
    if (body.aspectRatio !== undefined) updateData.aspectRatio = body.aspectRatio;
    if (body.model !== undefined) updateData.model = body.model;
    if (body.includeCharacters !== undefined) updateData.includeCharacters = body.includeCharacters;
    if (body.characterIds !== undefined) updateData.characterIds = body.characterIds;
    if (body.styleLabel !== undefined) updateData.styleLabel = body.styleLabel;
    if (body.status !== undefined) updateData.status = body.status;

    // If user flips this opening to series-default, demote any other opening in the same series.
    if (body.isSeriesDefault === true) {
      const seriesId = season.seriesId;
      await prisma.$transaction([
        prisma.seasonOpening.updateMany({
          where: {
            season: { seriesId },
            NOT: { id: existing.id },
          },
          data: { isSeriesDefault: false },
        }),
        prisma.seasonOpening.update({
          where: { id: existing.id },
          data: { ...updateData, isSeriesDefault: true },
        }),
      ]);
    } else {
      if (body.isSeriesDefault === false) updateData.isSeriesDefault = false;
      await prisma.seasonOpening.update({ where: { id: existing.id }, data: updateData });
    }

    const fresh = await prisma.seasonOpening.findUnique({
      where: { seasonId: params.id },
      include: { versions: { orderBy: { createdAt: "desc" }, take: 30 } },
    });
    return ok({ opening: fresh });
  } catch (e) { return handleError(e); }
}

export async function DELETE(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const ctx = await authenticate(req); if (isAuthResponse(ctx)) return ctx;
    const f = requirePermission(ctx, "edit_project"); if (f) return f;
    await assertSeason(params.id, ctx.organizationId);
    await prisma.seasonOpening.deleteMany({ where: { seasonId: params.id } });
    return ok({ deleted: true });
  } catch (e) { return handleError(e); }
}
