// Curated list of 100+ free AI + cinema tutorial URLs for bulk import.
// All public pages — no paywall, no login. Scraper (generic) extracts
// title + sections + images into guide structure.

export const GUIDE_CATALOG = {
  ai: [
    // Anthropic
    "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview",
    "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/be-clear-and-direct",
    "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/multishot-prompting",
    "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/chain-of-thought",
    "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/use-xml-tags",
    "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/system-prompts",
    "https://docs.anthropic.com/en/docs/build-with-claude/tool-use",
    "https://docs.anthropic.com/en/docs/build-with-claude/vision",
    // OpenAI Cookbook (via GitHub raw HTML)
    "https://platform.openai.com/docs/guides/prompt-engineering",
    "https://platform.openai.com/docs/guides/text-generation",
    "https://platform.openai.com/docs/guides/function-calling",
    "https://platform.openai.com/docs/guides/embeddings",
    "https://platform.openai.com/docs/guides/vision",
    "https://platform.openai.com/docs/guides/fine-tuning",
    // Google AI
    "https://ai.google.dev/gemini-api/docs/prompting-strategies",
    "https://ai.google.dev/gemini-api/docs/long-context",
    "https://ai.google.dev/gemini-api/docs/function-calling",
    "https://ai.google.dev/gemini-api/docs/vision",
    "https://ai.google.dev/gemini-api/docs/video-understanding",
    "https://ai.google.dev/gemini-api/docs/audio",
    "https://ai.google.dev/gemini-api/docs/embeddings",
    // LangChain
    "https://python.langchain.com/docs/tutorials/llm_chain",
    "https://python.langchain.com/docs/tutorials/chatbot",
    "https://python.langchain.com/docs/tutorials/rag",
    "https://python.langchain.com/docs/tutorials/agents",
    "https://python.langchain.com/docs/tutorials/qa_chat_history",
    // Hugging Face
    "https://huggingface.co/docs/transformers/quicktour",
    "https://huggingface.co/docs/transformers/pipeline_tutorial",
    "https://huggingface.co/docs/transformers/llm_tutorial",
    "https://huggingface.co/docs/diffusers/tutorials/basic_training",
    "https://huggingface.co/docs/diffusers/using-diffusers/text-img2img",
    // fal.ai
    "https://docs.fal.ai/model-apis/basics",
    "https://docs.fal.ai/model-apis/image-to-video",
    "https://docs.fal.ai/model-apis/text-to-video",
    // Replicate
    "https://replicate.com/docs/get-started/python",
    "https://replicate.com/docs/guides/push-a-model",
    // Real Python AI tutorials
    "https://realpython.com/generative-ai-python/",
    "https://realpython.com/chatgpt-api-python-chatbot/",
    "https://realpython.com/python-ai-neural-network/",
    "https://realpython.com/practical-prompt-engineering/",
    // fast.ai
    "https://www.fast.ai/posts/2023-09-04-learning-jumps/",
    // Prompt Engineering Guide
    "https://www.promptingguide.ai/introduction",
    "https://www.promptingguide.ai/techniques/zeroshot",
    "https://www.promptingguide.ai/techniques/fewshot",
    "https://www.promptingguide.ai/techniques/cot",
    "https://www.promptingguide.ai/techniques/consistency",
    "https://www.promptingguide.ai/techniques/rag",
    "https://www.promptingguide.ai/techniques/react",
    "https://www.promptingguide.ai/techniques/tot",
    // DeepLearning.AI blog
    "https://www.deeplearning.ai/the-batch/issue-230/",
  ],
  cinema: [
    // No Film School
    "https://nofilmschool.com/what-is-cinematography",
    "https://nofilmschool.com/what-is-a-dolly-shot",
    "https://nofilmschool.com/what-is-a-tracking-shot",
    "https://nofilmschool.com/types-of-camera-shots",
    "https://nofilmschool.com/three-point-lighting",
    "https://nofilmschool.com/rule-of-thirds-composition",
    "https://nofilmschool.com/what-is-color-grading",
    "https://nofilmschool.com/what-is-a-dutch-angle",
    // StudioBinder
    "https://www.studiobinder.com/blog/types-of-camera-shots-sizes-in-film/",
    "https://www.studiobinder.com/blog/types-of-camera-movements-in-film/",
    "https://www.studiobinder.com/blog/what-is-cinematography-definition/",
    "https://www.studiobinder.com/blog/what-is-cinematic-lighting-definition/",
    "https://www.studiobinder.com/blog/what-is-depth-of-field/",
    "https://www.studiobinder.com/blog/what-is-composition-in-film/",
    "https://www.studiobinder.com/blog/what-is-rack-focus-definition-and-examples/",
    "https://www.studiobinder.com/blog/what-is-anamorphic-lens/",
    "https://www.studiobinder.com/blog/what-is-a-close-up-shot/",
    "https://www.studiobinder.com/blog/what-is-a-wide-shot/",
    "https://www.studiobinder.com/blog/what-is-a-medium-shot/",
    "https://www.studiobinder.com/blog/what-is-an-establishing-shot/",
    "https://www.studiobinder.com/blog/what-is-an-over-the-shoulder-shot/",
    "https://www.studiobinder.com/blog/what-is-low-angle-shot-examples/",
    "https://www.studiobinder.com/blog/what-is-a-high-angle-shot/",
    "https://www.studiobinder.com/blog/film-genres-list/",
    "https://www.studiobinder.com/blog/what-is-film-noir/",
    "https://www.studiobinder.com/blog/what-is-cyberpunk/",
    "https://www.studiobinder.com/blog/what-is-chiaroscuro-definition/",
    "https://www.studiobinder.com/blog/what-is-golden-hour/",
    "https://www.studiobinder.com/blog/what-is-blue-hour-photography/",
    "https://www.studiobinder.com/blog/what-is-volumetric-lighting/",
    "https://www.studiobinder.com/blog/what-is-a-whip-pan/",
    "https://www.studiobinder.com/blog/what-is-a-crane-shot/",
    "https://www.studiobinder.com/blog/what-is-a-jib-shot/",
    "https://www.studiobinder.com/blog/what-is-a-pov-shot/",
    "https://www.studiobinder.com/blog/what-is-a-macro-shot/",
    "https://www.studiobinder.com/blog/what-is-slow-motion-in-film/",
    "https://www.studiobinder.com/blog/what-is-a-long-take-film/",
    "https://www.studiobinder.com/blog/what-is-lens-flare/",
    "https://www.studiobinder.com/blog/film-stock-explained/",
    "https://www.studiobinder.com/blog/what-is-a-35mm-lens/",
    "https://www.studiobinder.com/blog/what-is-a-50mm-lens/",
    "https://www.studiobinder.com/blog/what-is-an-85mm-lens/",
    "https://www.studiobinder.com/blog/what-is-f-stop-aperture/",
    "https://www.studiobinder.com/blog/what-is-iso-in-photography/",
    "https://www.studiobinder.com/blog/what-is-shutter-speed/",
    "https://www.studiobinder.com/blog/three-act-structure/",
    "https://www.studiobinder.com/blog/what-is-a-montage/",
    "https://www.studiobinder.com/blog/mise-en-scene-definition/",
    "https://www.studiobinder.com/blog/what-is-a-match-cut/",
    "https://www.studiobinder.com/blog/what-is-a-jump-cut/",
    "https://www.studiobinder.com/blog/what-is-an-l-cut-j-cut/",
    "https://www.studiobinder.com/blog/what-is-continuity-editing/",
    // Premium Beat / Shutterstock
    "https://www.premiumbeat.com/blog/the-ultimate-guide-to-3-point-lighting/",
    "https://www.premiumbeat.com/blog/what-is-color-grading/",
    "https://www.premiumbeat.com/blog/free-cinematic-luts/",
    "https://www.premiumbeat.com/blog/film-vs-digital-cinematography/",
    "https://www.premiumbeat.com/blog/cinematography-how-to-shoot-dream-sequences/",
  ],
};

export type CatalogKey = keyof typeof GUIDE_CATALOG;
