export declare const ROLES: readonly ["SUPER_ADMIN", "ADMIN", "DIRECTOR", "CONTENT_EDITOR", "AI_OPERATOR", "FINANCE_VIEWER", "VIEWER"];
export type RoleName = (typeof ROLES)[number];
export declare const PERMISSIONS: readonly ["manage_users", "manage_roles", "manage_providers", "manage_tokens", "view_finance", "manage_finance", "create_project", "edit_project", "delete_project", "manage_distribution", "generate_assets", "approve_scene", "publish_episode", "manage_ai_director", "view_logs", "manage_music", "manage_subtitles", "manage_dubbing", "manage_api_keys", "manage_webhooks", "manage_organization", "manage_templates", "manage_calendar", "view_audience_insights"];
export type PermissionKey = (typeof PERMISSIONS)[number];
export declare const PROVIDER_CATEGORIES: readonly ["VIDEO", "IMAGE", "AUDIO", "DUBBING", "MUSIC", "SUBTITLE", "DISTRIBUTION"];
export declare const ORG_PLANS: readonly ["FREE", "PRO", "STUDIO", "ENTERPRISE"];
export type OrgPlanName = (typeof ORG_PLANS)[number];
export declare const PLAN_LIMITS: Record<OrgPlanName, {
    maxProjects: number;
    maxEpisodes: number;
    autopilot: boolean;
    whitelabel: boolean;
}>;
export declare const QUEUE_NAMES: {
    readonly STORYBOARD: "storyboard-generation";
    readonly VIDEO: "video-generation";
    readonly MUSIC: "music-generation";
    readonly SUBTITLE: "subtitle-generation";
    readonly DUBBING: "dubbing-generation";
    readonly LIPSYNC: "lip-sync-generation";
    readonly AVATAR: "avatar-generation";
    readonly DIALOGUE: "dialogue-generation";
    readonly CRITIC: "critic-review";
    readonly SEO: "seo-generation";
    readonly STYLE_SNAPSHOT: "style-snapshot";
    readonly SCRIPT_BREAKDOWN: "script-breakdown";
    readonly PUBLISHING: "publishing";
    readonly ANALYTICS: "analytics-sync";
    readonly AUDIENCE_INSIGHTS: "audience-insights";
    readonly MEMORY: "memory-refresh";
    readonly RECAP: "recap-generation";
    readonly WEBHOOK_DELIVERY: "webhook-delivery";
    readonly INCOMING_WEBHOOK: "incoming-webhook";
};
export declare const QUEUE_PRIORITY: Record<string, number>;
export declare const NOTIFICATION_TYPES: readonly ["JOB_DONE", "JOB_FAILED", "EPISODE_READY", "BUDGET_WARNING", "PUBLISH_SUCCESS"];
export declare const WEBHOOK_EVENTS: readonly ["episode.published", "episode.failed", "job.completed", "job.failed", "scene.approved", "budget.warning"];
