/**
 * POST /api/v1/projects/[id]/cast-composite
 *   Build (or rebuild) a single composite image laying out every character
 *   in the project side-by-side with their names. Used as a one-shot identity
 *   reference for Sora / VEO / Vidu so multi-character scenes get all faces
 *   locked, not just the first one.
 *
 *   Body: { characterIds?: string[] }  — optional; defaults to ALL characters.
 *
 * GET /api/v1/projects/[id]/cast-composite
 *   Returns the latest composite Asset (or null).
 */
import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { authenticate, requirePermission, isAuthResponse } from "@/lib/auth";
import { buildOpeningCompositeReference } from "@/lib/providers/build-opening-composite";
import { handleError, ok } from "@/lib/route-utils";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

async function assertProject(projectId: string, orgId: string) {
  const p = await prisma.project.findFirst({
    where: { id: projectId, organizationId: orgId },
    select: { id: true },
  });
  if (!p) throw Object.assign(new Error("project not found"), { statusCode: 404 });
  return p;
}

const Body = z.object({ characterIds: z.array(z.string()).optional() });

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const ctx = await authenticate(req); if (isAuthResponse(ctx)) return ctx;
    const f = requirePermission(ctx, "edit_project"); if (f) return f;
    await assertProject(params.id, ctx.organizationId);
    const body = Body.parse(await req.json().catch(() => ({})));

    const chars = await prisma.character.findMany({
      where: {
        projectId: params.id,
        ...(body.characterIds?.length ? { id: { in: body.characterIds } } : {}),
      },
      include: { media: { orderBy: { createdAt: "asc" } } },
      orderBy: { createdAt: "asc" },
    });
    if (chars.length === 0) throw Object.assign(new Error("no characters to composite"), { statusCode: 400 });

    const composite = await buildOpeningCompositeReference(
      params.id,
      chars.map((c) => ({ id: c.id, name: c.name, media: c.media })),
    );

    // Persist as a PROJECT-scoped Asset so the characters page + wizard can
    // pull it without rebuilding on every view. metadata.kind identifies it.
    const asset = await prisma.asset.create({
      data: {
        projectId: params.id,
        entityType: "PROJECT",
        entityId: params.id,
        assetType: "IMAGE",
        fileUrl: composite.compositeUrl,
        mimeType: "image/jpeg",
        status: "READY",
        metadata: {
          kind: "cast-composite",
          characterCount: composite.characterCount,
          characterIds: chars.map((c) => c.id),
          characterNames: chars.map((c) => c.name),
          layoutDescription: composite.layoutDescription,
          autoGenerated: true,
          builtAt: new Date().toISOString(),
          builtBy: ctx.user.id,
        } as any,
      },
    });

    return ok({
      asset: { id: asset.id, fileUrl: asset.fileUrl, createdAt: asset.createdAt },
      compositeUrl: composite.compositeUrl,
      layoutDescription: composite.layoutDescription,
      characterCount: composite.characterCount,
      characterNames: chars.map((c) => c.name),
    });
  } catch (e) {
    return handleError(e);
  }
}

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const ctx = await authenticate(req); if (isAuthResponse(ctx)) return ctx;
    await assertProject(params.id, ctx.organizationId);

    const latest = await prisma.asset.findFirst({
      where: {
        projectId: params.id,
        entityType: "PROJECT",
        assetType: "IMAGE",
        metadata: { path: ["kind"], equals: "cast-composite" },
      },
      orderBy: { createdAt: "desc" },
      select: { id: true, fileUrl: true, createdAt: true, metadata: true },
    });

    return ok({ composite: latest });
  } catch (e) {
    return handleError(e);
  }
}
