/**
 * POST /api/v1/scenes/[id]/remix-suggest
 * The AI Director reviews the scene's full context (script, director sheet,
 * sound notes, episode synopsis, series bible) and proposes specific remix
 * notes to improve the existing Sora video — using the 6-layer formula.
 */
import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { authenticate, isAuthResponse } from "@/lib/auth";
import { groqChat } from "@/lib/groq";
import { getContext } from "@/lib/project-context";
import { handleError, ok } from "@/lib/route-utils";

export const runtime = "nodejs"; export const dynamic = "force-dynamic"; export const maxDuration = 60;

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const ctx = await authenticate(req); if (isAuthResponse(ctx)) return ctx;

    const scene = await prisma.scene.findFirst({
      where: { id: params.id },
      include: {
        episode: {
          include: {
            season: { include: { series: { include: { project: true } } } },
            scenes: { orderBy: { sceneNumber: "asc" }, select: { sceneNumber: true, title: true, summary: true } },
          },
        },
      },
    });
    if (!scene) throw Object.assign(new Error("scene not found"), { statusCode: 404 });

    const mem = (scene.memoryContext as {
      directorSheet?: Record<string, string>;
      directorNotes?: string;
      soundNotes?: string;
      characters?: string[];
      mood?: string;
      location?: string;
    } | null) ?? {};

    const project = scene.episode?.season.series.project;
    const bible = project ? (await getContext(project.id))?.summary ?? project.description ?? "" : "";
    const epScenes = scene.episode?.scenes ?? [];
    const prevScene = epScenes.find((s) => s.sceneNumber === scene.sceneNumber - 1);
    const nextScene = epScenes.find((s) => s.sceneNumber === scene.sceneNumber + 1);

    // Past activity on this scene: previous critic reviews, remixes,
    // director-sheet edits, sound-notes regenerations. The director reads
    // this so each new remix compounds on prior notes instead of repeating.
    const pastLogs: Array<{ action: string; details: any; createdAt: Date; actorName: string | null }> = await (prisma as any).sceneLog.findMany({
      where: { sceneId: scene.id },
      orderBy: { createdAt: "desc" },
      take: 12,
      select: { action: true, details: true, createdAt: true, actorName: true },
    });
    const pastCritics = await prisma.aICriticReview.findMany({
      where: { sceneId: scene.id },
      orderBy: { createdAt: "desc" },
      take: 3,
      select: { score: true, feedback: true, createdAt: true },
    }).catch(() => []);

    const system = `You are the AI Director of "${project?.name ?? "the series"}". You know every episode, scene, and character intimately. A scene video was already generated by Sora 2. The user wants to REMIX it (Sora keeps identity+motion, changes only what you specify).

Write 4-6 specific remix notes using the 6-layer formula. Focus on what will make this scene feel like a real TV production:
1. SUBJECT — skin pores, hair strands, wardrobe fabric wrinkles
2. ACTION — micro-expressions, breathing, weight shifts
3. ENVIRONMENT — specific props, weather particles, background extras
4. STYLE — film stock reference (Alexa 35, RED V-Raptor), color grade name
5. LIGHTING — key/fill/rim positions, color temperature in Kelvin, practicals
6. TECHNICAL — lens mm, f-stop, focus rack, camera movement name

Also consider continuity: how should this scene CONNECT visually to the previous and next scenes (lighting match, color palette carry-over, matching eye-lines).

End with a fade-to-black note for the last 0.5 seconds.

Output in English (Sora prompt language). Be specific — no generic "cinematic lighting". Name the exact technique.`;

    const user = [
      `SERIES: ${project?.name ?? "?"} · ${project?.genreTag ?? "drama"}`,
      `BIBLE EXCERPT: ${bible.slice(0, 600)}`,
      `EPISODE: EP${scene.episode?.episodeNumber} "${scene.episode?.title ?? ""}"`,
      prevScene && `PREV SCENE (SC${prevScene.sceneNumber}): ${prevScene.summary?.slice(0, 150) ?? prevScene.title}`,
      `THIS SCENE (SC${scene.sceneNumber}): "${scene.title}"`,
      scene.summary && `Summary: ${scene.summary}`,
      scene.scriptText && `Script:\n${scene.scriptText.slice(0, 800)}`,
      mem.directorSheet && `Director sheet:\n${Object.entries(mem.directorSheet).map(([k, v]) => `  ${k}: ${String(v).slice(0, 100)}`).join("\n")}`,
      mem.soundNotes && `Sound notes (excerpt): ${mem.soundNotes.slice(0, 300)}`,
      mem.characters?.length && `Characters in scene: ${mem.characters.join(", ")}`,
      mem.mood && `Mood: ${mem.mood}`,
      mem.location && `Location: ${mem.location}`,
      nextScene && `NEXT SCENE (SC${nextScene.sceneNumber}): ${nextScene.summary?.slice(0, 150) ?? nextScene.title}`,
      pastLogs.length > 0 && `PRIOR ACTIVITY ON THIS SCENE (most recent first) — read carefully and don't duplicate notes already applied:\n${pastLogs.map((l) => `  · ${l.createdAt.toISOString().slice(0, 16)} ${l.action}${l.actorName ? ` by ${l.actorName}` : ""}${l.details ? ` — ${JSON.stringify(l.details).slice(0, 200)}` : ""}`).join("\n")}`,
      pastCritics.length > 0 && `PRIOR CRITIC REVIEWS (${pastCritics.length}):\n${pastCritics.map((c: any) => `  · score=${(c.score * 100).toFixed(0)}% — ${String(c.feedback ?? "").slice(0, 300)}`).join("\n")}`,
    ].filter(Boolean).join("\n\n");

    const suggestion = await groqChat(
      [{ role: "system", content: system }, { role: "user", content: user }],
      { temperature: 0.7, maxTokens: 800, description: `Remix suggest · SC${scene.sceneNumber}` },
    );

    // SceneLog + CostEntry
    await (prisma as any).sceneLog.create({
      data: {
        sceneId: scene.id,
        action: "remix_suggest",
        actor: `user:${ctx.user.id}`,
        actorName: ctx.user.fullName ?? ctx.user.email,
        details: { preview: suggestion.trim().slice(0, 200) },
      },
    }).catch(() => {});
    const projectId = project?.id;
    if (projectId) {
      const { chargeUsd } = await import("@/lib/billing");
      await chargeUsd({
        organizationId: ctx.organizationId, projectId,
        entityType: "SCENE", entityId: scene.id,
        providerName: "Groq", category: "TOKEN",
        description: `AI Director remix suggest · scene ${scene.sceneNumber}`,
        unitCost: 0.005, quantity: 1, userId: ctx.user.id,
      }).catch(() => {});
    }

    return ok({ sceneId: scene.id, suggestion: suggestion.trim() });
  } catch (e) { return handleError(e); }
}
